### ISSUE TITLE
[Feature] Insert react component inside ticker

### ISSUE THREAD

**Issue by HighSoftWare96** [deanhet/react-native-text-ticker#20]
I was wondering if there will be the chance to add the feature reported in the title, so I can insert without problems this kind of component inside the TextTicker:
```
<TextTicker>
       <Text style={style1}>1</Text>
        <Text style={style2}>2</Text>
</TextTicker>
```
Right now this is "possible" only inserting an array of objects inside the TextTicker but this causes a bug that does not animate the text correctly.

**Comment by deanhet** [comment]
Components inside of ticker is kind of going beyond the scope of what I intended this package to do. It just scrolls text.
React native allows you to embed `<Text>` within each other, have you tried something like:

```
 <Text style={style1}>
    1
    <Text style={style2}>2</Text>
</Text>
```

Otherwise this package probably isn't suitable for what you need. Would go with putting all your content in an `Animated.View` and transforming the `translateY` (similar to this package's source)

**Comment by HighSoftWare96** [comment]
I think I can't insert a <Text /> inside the TextTicker because it generates anomalies in the animation and it is not a valid props, so I can't use your solution..
But thanks for the reply, this is a well built library!
