### ISSUE TITLE
How can I make texts still loop scroll, even through texts fit container ?

### ISSUE THREAD

**Issue by jamessawyer** [deanhet/react-native-text-ticker#24]
Thanks for the awesome lib! Now I wanna my texts scroll loop, even texts are short, how can I achieve this effect?

**Comment by deanhet** [comment]
Thanks!
Its been a while since I looked at the code but it seems like you're right. If the text is small enough to fit then there's no way to make it still scroll.

The code that makes it happen is on line 191 in index.js.
I'd be happy to accept a pull request that adds a new prop to override this.

Something like: 
```
  shouldBounce: (this.props.forceBounce) || this.distance < this.containerWidth / 8
```

**Comment by jamessawyer** [comment]
I've tried your advise, add a prop 'forceBounce' to the lib, but it didn't work. What's more, it would make loop feature fail, LoL~

**Comment by deanhet** [comment]
#25 Will be going out in the latest release and should fix your issue

**Comment by esbb48** [comment]
Thanks for the library, too 👍 

hmm may I seek the reason why `forceBounce` be remove in new version? QQ.
