### ISSUE TITLE
TypeError:expected dynamic type 'double',but had type null (constructing arguments for UIManager.measure at argument index 0)

### ISSUE THREAD

**Issue by imtmh** [deanhet/react-native-text-ticker#4]
![screenshot_1527777576](https://user-images.githubusercontent.com/2740042/40789008-08b6adf8-650f-11e8-879e-65a07eca8fcc.png)

I got the above error, 
Currently, I am using the TextTicker for the header, so Its working for the first screen, but when i navigate to the second screen the above error is popping up.
```

  _renderTitle = (title) => {

    const node = (
      this.props.htmlContent
        ? <HTMLView value={`<span>${title}</span>`} stylesheet={styles} />
        : <View>
          <TextTicker
            style={styles.title}
            duration={5000}
            loop
            bounce
            repeatSpacer={50}
            marqueeDelay={1000}
          >
            {title}
          </TextTicker>
        </View>
    )
    return node
  }
```

Am I doing something wrong here? or issue with something else?

**Comment by deanhet** [comment]
Hi there!
Sorry, it's really difficult to get a feel for what's wrong here. I don't have an android device either so I can't try and replicate it for you.
A complete shot in the dark is try putting a default value for your title while it loads(?). It looks like the function that measures the length of the text is returning `null`, maybe because the title isn't there to begin with.

Try something like 
```
<TextTicker
  ...
>
  {title || 'Default title'}
</TextTicker>

Let me know how you get on.

**Comment by imtmh** [comment]
Let me try this and get back on this.

**Comment by deanhet** [comment]
Not a clue to be honest! I can't really imagine how the two would be linked, wouldn't really be able to tell without checking the codebase. 
I'm glad you found some form of resolution though. I'm going to mark this as closed but do file another issue if you have any more problems.
